'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version:2.0.40120.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.IO
Imports System.Resources


'This class was auto-generated by the Strongly Typed Resource Builder
'class via a tool like ResGen or Visual Studio.NET.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
NotInheritable Class MyResources
    
    Private Shared _resMgr As System.Resources.ResourceManager
    
    Private Sub New()
        MyBase.New
    End Sub
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared ReadOnly Property ResourceManager() As System.Resources.ResourceManager
        Get
            If (_resMgr Is Nothing) Then
                Dim temp As System.Resources.ResourceManager = New System.Resources.ResourceManager(GetType(MyResources))
                System.Threading.Thread.MemoryBarrier
                _resMgr = temp
            End If
            Return _resMgr
        End Get
    End Property
End Class
